version: "3.7"

services:
    db:
        container_name: postgres
        image: postgres:15.2
        restart: always
        environment:
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_DB=${POSTGRES_DB}
            - PGDATA=/data/postgres
        ports:
            - 5432:5432
        volumes:
            - ./postgres_data:/data/postgres
        networks:
            - backend

volumes:
    postgres_data:

networks:
    backend:
